name: Python application

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, '3.10']
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt

      - name: Lint
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --max-line-length 120 --show-source --statistics
          
          # stop the build if sorting is in wrong order
          isort . -c

      - name: Test
        run: |
          coverage run -m unittest
          
          # print coverage
          coverage report
